"""empty message

Revision ID: 06a5f3486077
Revises: 44851d6422f4
Create Date: 2025-11-04 22:14:50.929090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a5f3486077'
down_revision = '44851d6422f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=1000), nullable=True))
        batch_op.alter_column('mensagem',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('mensagem',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
