"""Adiciona coluna lastname ao modelo User

Revision ID: 10e8d894318a
Revises: 480e1330f7b4
Create Date: 2025-10-22 21:14:51.743914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10e8d894318a'
down_revision = '480e1330f7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=150), nullable=False))
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
