"""correção do nome repondido para respondido

Revision ID: 21e8aef29cf7
Revises: 663b814451c8
Create Date: 2025-09-29 20:18:38.475769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e8aef29cf7'
down_revision = '663b814451c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))
        batch_op.drop_column('repondido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repondido', sa.INTEGER(), nullable=True))
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
