"""Inclusão de campo respondido na tabela contato

Revision ID: 663b814451c8
Revises: 34e977f35924
Create Date: 2025-09-29 20:08:09.264806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663b814451c8'
down_revision = '34e977f35924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('repondido')

    # ### end Alembic commands ###
