"""Adiciona coluna imagem à tabela post

Revision ID: cb4dc29433f4
Revises: 06a5f3486077
Create Date: 2025-11-04 22:52:57.066116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4dc29433f4'
down_revision = '06a5f3486077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('imagem',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
